project_id = "ilxoaamccqayhcwcxevc"

[functions.chat]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.generate-caption]
verify_jwt = false

[functions.generate-video]
verify_jwt = false
